pull_request_title: 'feat(l10n): localization updates'
pull_request_assignees:
  - 'michaldrabik'
commit_message: 'feat(l10n): %language% localization updates'
append_commit_message: false
bundles:
  - 2
