package tv.trakt.trakt.tv.networking.openapi

import org.openapitools.client.models.GetCalendarsMovies200ResponseInner
import org.openapitools.client.models.GetCalendarsMovies200ResponseInnerIds
import org.openapitools.client.models.GetCalendarsShows200ResponseInner
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerEpisode
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerEpisodeIds
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerShow
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerShowIds
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerShowImages
import org.openapitools.client.models.GetMoviesPeople200Response
import org.openapitools.client.models.GetMoviesPeople200ResponseCastInnerPerson
import org.openapitools.client.models.GetMoviesRatings200Response
import org.openapitools.client.models.GetMoviesVideos200ResponseInner
import org.openapitools.client.models.GetMoviesWatchnow200ResponseValue
import org.openapitools.client.models.GetPeopleMovies200Response
import org.openapitools.client.models.GetPeopleShows200Response
import org.openapitools.client.models.GetPeopleSummary200Response
import org.openapitools.client.models.GetRecommendationsMoviesRecommend200ResponseInner
import org.openapitools.client.models.GetRecommendationsShowsRecommend200ResponseInner
import org.openapitools.client.models.GetSyncProgressUpNextStandard200ResponseInner
import org.openapitools.client.models.GetSyncProgressUpNextStandard200ResponseInnerProgressLastEpisode
import org.openapitools.client.models.GetUsersComments200ResponseInnerOneOf2Season
import org.openapitools.client.models.GetUsersComments200ResponseInnerOneOfComment
import org.openapitools.client.models.GetUsersFavoritesMovies200ResponseInner
import org.openapitools.client.models.GetUsersFavoritesShows200ResponseInner
import org.openapitools.client.models.GetUsersHistoryAll200ResponseInner
import org.openapitools.client.models.GetUsersHistoryAll200ResponseInnerOneOf
import org.openapitools.client.models.GetUsersHistoryAll200ResponseInnerOneOf1
import org.openapitools.client.models.GetUsersLikesComments200ResponseInnerAllOfCommentUser
import org.openapitools.client.models.GetUsersListsPersonal200ResponseInner
import org.openapitools.client.models.GetUsersSettings200Response
import org.openapitools.client.models.GetUsersWatchedMovies200ResponseInner
import org.openapitools.client.models.GetUsersWatchedShows200ResponseInner
import org.openapitools.client.models.GetUsersWatchlistMovies200ResponseInner
import org.openapitools.client.models.GetUsersWatchlistShows200ResponseInner
import org.openapitools.client.models.GetWatchnowSourcesAll200ResponseInnerValueInner
import org.openapitools.client.models.PostSyncHistoryAdd200Response

/**
 * Type aliases for OpenAPI models used in the app.
 */
internal typealias ShowDto = GetCalendarsShows200ResponseInnerShow
internal typealias ShowIdsDto = GetCalendarsShows200ResponseInnerShowIds

internal typealias MovieDto = GetCalendarsMovies200ResponseInner
internal typealias MovieIdsDto = GetCalendarsMovies200ResponseInnerIds

internal typealias EpisodeDto = GetCalendarsShows200ResponseInnerEpisode
internal typealias LastEpisodeDto = GetSyncProgressUpNextStandard200ResponseInnerProgressLastEpisode
internal typealias EpisodeIdsDto = GetCalendarsShows200ResponseInnerEpisodeIds

internal typealias ImagesDto = GetCalendarsShows200ResponseInnerShowImages
internal typealias ExtraVideoDto = GetMoviesVideos200ResponseInner
internal typealias CastCrewDto = GetMoviesPeople200Response
internal typealias ExternalRatingsDto = GetMoviesRatings200Response
internal typealias PersonDto = GetMoviesPeople200ResponseCastInnerPerson
internal typealias PersonDetailsDto = GetPeopleSummary200Response
internal typealias PersonShowsDto = GetPeopleShows200Response
internal typealias PersonMoviesDto = GetPeopleMovies200Response
internal typealias CommentDto = GetUsersComments200ResponseInnerOneOfComment
internal typealias SeasonDto = GetUsersComments200ResponseInnerOneOf2Season
internal typealias ListDto = GetUsersListsPersonal200ResponseInner
internal typealias ListMovieItemDto = GetUsersWatchlistMovies200ResponseInner
internal typealias ListShowItemDto = GetUsersWatchlistShows200ResponseInner
internal typealias UserDto = GetUsersLikesComments200ResponseInnerAllOfCommentUser
internal typealias UserSettingsDto = GetUsersSettings200Response
internal typealias StreamingDto = GetMoviesWatchnow200ResponseValue
internal typealias StreamingSourceDto = GetWatchnowSourcesAll200ResponseInnerValueInner
internal typealias WatchlistShowDto = GetUsersWatchlistShows200ResponseInner
internal typealias WatchlistMovieDto = GetUsersWatchlistMovies200ResponseInner
internal typealias CalendarShowDto = GetCalendarsShows200ResponseInner
internal typealias ProgressShowDto = GetSyncProgressUpNextStandard200ResponseInner
internal typealias WatchedShowDto = GetUsersWatchedShows200ResponseInner
internal typealias WatchedMovieDto = GetUsersWatchedMovies200ResponseInner
internal typealias SyncAddHistoryResponseDto = PostSyncHistoryAdd200Response
internal typealias SyncHistoryMovieItemDto = GetUsersHistoryAll200ResponseInnerOneOf
internal typealias SyncHistoryEpisodeItemDto = GetUsersHistoryAll200ResponseInnerOneOf1
internal typealias SyncHistoryAllItemDto = GetUsersHistoryAll200ResponseInner
internal typealias SyncFavoriteShowDto = GetUsersFavoritesShows200ResponseInner
internal typealias SyncFavoriteMovieDto = GetUsersFavoritesMovies200ResponseInner
internal typealias RecommendedMovieDto = GetRecommendationsMoviesRecommend200ResponseInner
internal typealias RecommendedShowDto = GetRecommendationsShowsRecommend200ResponseInner
