package tv.trakt.trakt.common.ui.theme.colors

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

val DarkColors: TraktColors = TraktColors(
    accent = Purple500,
    backgroundPrimary = Shade920,
    textPrimary = White,
    textSecondary = Shade300,
    skeletonContainer = Shade910,
    skeletonShimmer = Shade900,
    placeholderContainer = Shade800,
    placeholderContent = Shade600,
    tagChipContent = White,
    tagChipContainer = Shade700,
    tagChipContainerLight = Shade500,
    chipContainer = Shade700,
    chipContainerOnContent = Shade700.copy(alpha = 0.64F),
    chipContent = White,
    navigationHeaderContainer = Shade900.copy(alpha = 0.98F),
    navigationContainer = Shade900.copy(alpha = 0.98F),
    navigationContent = White,
    navigationContentOn = Purple400,
    navigationContentOff = Shade300,
    inputContainer = Shade920,
    dialogContainer = Shade900,
    dialogOnContainer = Shade800,
    dialogContent = Shade800,
    panelCardContainer = Shade900,
    commentContainer = Shade900,
    commentReplyContainer = Shade800,
    customListContainer = Shade900,
    sentimentsContainer = Purple940,
    sentimentsAccent = White,
    sentimentsGoodAccent = Purple100,
    sentimentsBadAccent = Red80,
    triviaContainer = Purple940,
    triviaAccent = Purple40,
    detailsStatus1 = Purple300,
    detailsStatus2 = Purple100,
    vipAccent = Purple500,
    separator = Shade800,
    // Buttons
    primaryButtonContainer = Purple500,
    primaryButtonContainerDisabled = Shade700,
    primaryButtonContent = White,
    primaryButtonContentDisabled = White,
    // Snackbar
    snackbarContainer = White,
    snackbarContent = Shade940,
    // Switches
    switchContainerChecked = Purple800,
    switchContainerUnchecked = White,
    switchThumbChecked = Purple500,
    switchThumbUnchecked = Purple500,
)

@Immutable
data class TraktColors(
    val accent: Color = Color.Unspecified,
    val backgroundPrimary: Color = Color.Unspecified,
    val textPrimary: Color = Color.Unspecified,
    val textSecondary: Color = Color.Unspecified,
    val skeletonContainer: Color = Color.Unspecified,
    val skeletonShimmer: Color = Color.Unspecified,
    val tagChipContainer: Color = Color.Unspecified,
    val tagChipContainerLight: Color = Color.Unspecified,
    val tagChipContent: Color = Color.Unspecified,
    val chipContainer: Color = Color.Unspecified,
    val chipContainerOnContent: Color = Color.Unspecified,
    val chipContent: Color = Color.Unspecified,
    val placeholderContainer: Color = Color.Unspecified,
    val placeholderContent: Color = Color.Unspecified,
    val inputContainer: Color = Color.Unspecified,
    val dialogContainer: Color = Color.Unspecified,
    val dialogOnContainer: Color = Color.Unspecified,
    val dialogContent: Color = Color.Unspecified,
    val panelCardContainer: Color = Color.Unspecified,
    val commentContainer: Color = Color.Unspecified,
    val commentReplyContainer: Color = Color.Unspecified,
    val customListContainer: Color = Color.Unspecified,
    val sentimentsContainer: Color = Color.Unspecified,
    val sentimentsAccent: Color = Color.Unspecified,
    val sentimentsGoodAccent: Color = Color.Unspecified,
    val sentimentsBadAccent: Color = Color.Unspecified,
    val triviaContainer: Color = Color.Unspecified,
    val triviaAccent: Color = Color.Unspecified,
    val detailsStatus1: Color = Color.Unspecified,
    val detailsStatus2: Color = Color.Unspecified,
    val vipAccent: Color = Color.Unspecified,
    val separator: Color = Color.Unspecified,
    // Nav
    val navigationHeaderContainer: Color = Color.Unspecified,
    val navigationContainer: Color = Color.Unspecified,
    val navigationContent: Color = Color.Unspecified,
    val navigationContentOn: Color = Color.Unspecified,
    val navigationContentOff: Color = Color.Unspecified,
    // Buttons
    val primaryButtonContainer: Color = Color.Unspecified,
    val primaryButtonContainerDisabled: Color = Color.Unspecified,
    val primaryButtonContent: Color = Color.Unspecified,
    val primaryButtonContentDisabled: Color = Color.Unspecified,
    // Snackbar
    val snackbarContainer: Color = Color.Unspecified,
    val snackbarContent: Color = Color.Unspecified,
    // Switches
    val switchContainerChecked: Color = Color.Unspecified,
    val switchContainerUnchecked: Color = Color.Unspecified,
    val switchThumbChecked: Color = Color.Unspecified,
    val switchThumbUnchecked: Color = Color.Unspecified,
)
