package tv.trakt.trakt.common.ui.theme.colors

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

val DarkColors: TraktColors = TraktColors(
    isLight = false,
    accent = Purple500,
    backgroundPrimary = Shade920,
    backgroundImageAlpha = 0.4F,
    textPrimary = White,
    textPrimaryOnAccent = White,
    textSecondary = Shade300,
    skeletonContainer = Shade910,
    skeletonShimmer = Shade900,
    placeholderContainer = Shade800,
    placeholderContent = Shade600,
    tagChipContent = Black,
    tagChipContentOnAccent = White,
    tagChipContainer = White,
    tagChipContainerLight = Shade250,
    chipContainer = Shade700,
    chipContainerOnContent = Shade700.copy(alpha = 0.64F),
    chipContent = White,
    navigationHeaderContainer = Shade900.copy(alpha = 0.98F),
    navigationContainer = Shade900.copy(alpha = 0.98F),
    navigationContent = White,
    navigationContentOn = Purple400,
    navigationContentOff = Shade300,
    inputContainer = Shade920,
    dialogContainer = Shade900,
    dialogOnContainer = Shade800,
    dialogContent = Shade800,
    // Dropdowns
    dropdownContainer = Shade800,
    dropdownContainerActive = White,
    dropdownMenuContainer = Shade900,
    dropdownContent = Shade300,
    dropdownContentActive = Purple500,
    panelCardContainer = Shade900,
    commentContainer = Shade900,
    commentReplyContainer = Shade800,
    customListContainer = Shade900,
    customListGradient = Purple900,
    sentimentsContainer = Purple940,
    sentimentsAccent = White,
    sentimentsGoodAccent = Purple100,
    sentimentsBadAccent = Red80,
    triviaContainer = Purple940,
    triviaAccent = Purple40,
    detailsStatus1 = Purple300,
    detailsStatus2 = Purple100,
    vipAccent = Purple500,
    separator = Shade800,
    // Streaks
    streakTileEmpty = Shade800,
    streakTileToday = White,
    streakLevel1 = Purple920,
    streakLevel2 = Purple700,
    streakLevel3 = Purple500,
    streakLevel4 = Purple300,
    // Buttons
    primaryButtonContainer = Purple500,
    primaryButtonContainerDisabled = Shade700,
    primaryButtonContent = White,
    primaryButtonContentDisabled = White,
    ghostButtonContent = White,
    // Snackbar
    snackbarContainer = White,
    snackbarContent = Shade940,
    // Tooltip
    tooltipContainer = Shade800,
    tooltipContent = White,
    // Switches
    switchContainerChecked = Purple800,
    switchContainerUnchecked = White,
    switchThumbChecked = Purple500,
    switchThumbUnchecked = Purple500,
    // Reactions
    reactionsContainer = Shade800,
    reactionsSummaryContainer = Shade700,
    reactionsSummaryHighlight = Shade800,
    // Shadows
    shadowSmall = 1.dp,
    shadowDefault = 2.dp,
    shadowLarge = 3.dp,
    shadowDynamicSmall = 0.dp,
    shadowDynamicDefault = 0.dp,
    shadowDynamicLarge = 0.dp,
    // Misc
    profileStatsContainer = Shade920,
    profileStatsChip = Shade920,
    justWatchAccent = Color(0xFFfcc405),
)
