package tv.trakt.trakt.common.ui.theme.colors

import androidx.compose.ui.unit.dp

val LightColors: TraktColors = TraktColors(
    isLight = true,
    accent = Purple500,
    backgroundPrimary = Shade50,
    backgroundImageAlpha = 0.55F,
    textPrimary = Shade920,
    textPrimaryOnAccent = White,
    textSecondary = Shade500,
    skeletonContainer = Shade70,
    skeletonShimmer = Shade60,
    placeholderContainer = Shade70,
    placeholderContent = Shade150,
    tagChipContent = White,
    tagChipContentOnAccent = White,
    tagChipContainer = Shade900,
    tagChipContainerLight = Shade600,
    chipContainer = Shade200,
    chipContainerOnContent = Shade500.copy(alpha = 0.64F),
    chipContent = Shade900,
    navigationHeaderContainer = Shade20.copy(alpha = 0.98F),
    navigationContainer = Shade20.copy(alpha = 0.98F),
    navigationContent = Shade900,
    navigationContentOn = Purple600,
    navigationContentOff = Shade400,
    inputContainer = Shade50,
    dialogContainer = Shade40,
    dialogOnContainer = Shade10,
    dialogContent = Shade200,
    // Dropdowns
    dropdownContainer = Shade90,
    dropdownContainerActive = Purple500,
    dropdownMenuContainer = Shade40,
    dropdownContent = Shade500,
    dropdownContentActive = White,
    panelCardContainer = White,
    commentContainer = White,
    commentReplyContainer = Shade55,
    customListContainer = White,
    customListGradient = Purple200,
    sentimentsContainer = Purple150,
    sentimentsAccent = Shade900,
    sentimentsGoodAccent = Purple800,
    sentimentsBadAccent = Red700,
    triviaContainer = Purple150,
    triviaAccent = Purple800,
    detailsStatus1 = Purple600,
    detailsStatus2 = Purple800,
    vipAccent = Purple500,
    separator = Shade80,
    // Streaks
    streakTileEmpty = Shade80,
    streakTileToday = Shade920,
    streakLevel1 = Purple200,
    streakLevel2 = Purple400,
    streakLevel3 = Purple600,
    streakLevel4 = Purple800,
    // Buttons
    primaryButtonContainer = Purple500,
    primaryButtonContainerDisabled = Shade100,
    primaryButtonContent = White,
    primaryButtonContentDisabled = Shade400,
    ghostButtonContent = Shade920,
    // Snackbar
    snackbarContainer = Shade900,
    snackbarContent = White,
    // Tooltip
    tooltipContainer = Shade900,
    tooltipContent = White,
    // Switches
    switchContainerChecked = Purple300,
    switchContainerUnchecked = Shade90,
    switchThumbChecked = Purple500,
    switchThumbUnchecked = Shade500,
    // Reactions
    reactionsContainer = White,
    reactionsSummaryContainer = Shade50,
    reactionsSummaryHighlight = Shade100,
    // Shadows
    shadowSmall = 1.dp,
    shadowDefault = 2.dp,
    shadowLarge = 3.dp,
    shadowDynamicSmall = 1.dp,
    shadowDynamicDefault = 2.dp,
    shadowDynamicLarge = 3.dp,
    // Misc
    profileStatsContainer = Shade900,
    profileStatsChip = Shade910,
)
