/*
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package tv.trakt.trakt.core.people.data.remote.api

import io.ktor.client.HttpClientConfig
import io.ktor.client.engine.HttpClientEngine
import io.ktor.client.utils.EmptyContent
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.HttpResponse
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.wrap
import tv.trakt.trakt.common.networking.PersonDto

internal open class PeopleExtrasApi(
    baseUrl: String,
    httpClientEngine: HttpClientEngine?,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)?,
) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {
    @Suppress("UNCHECKED_CAST")
    open suspend fun getBirthdayPeople(extended: Any?): HttpResponse<List<PersonDto>> {
        val localVariableAuthNames = listOf<String>()

        val localVariableBody =
            EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        extended?.apply { localVariableQuery["extended"] = listOf("$extended") }

        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<Any?>(
            RequestMethod.GET,
            "/people/this_month",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames,
        ).wrap()
    }
}
