default_platform(:android)

platform :android do
  desc "Distribute a new version to me only"
  lane :firebase_distribute_me do
    gradle(
      task: "assembleRelease"
    )

    firebase_app_distribution(
      app: "1:213753735103:android:13d79e31e4663aea06230a",
      testers: "mike@trakt.tv",
      release_notes: ""
    )
  end

  desc "Distribute a new version to Internal Testers group"
  lane :firebase_distribute_internal do
    # Ask for optional release notes
    release_notes = prompt(
      text: "Enter release notes (optional, press Enter to skip): ",
      ci_input: ""
    )

    gradle(
      task: "assembleRelease"
    )

    firebase_app_distribution(
      app: "1:213753735103:android:13d79e31e4663aea06230a",
      groups: "trakt-internal-testers",
      release_notes: release_notes
    )
  end
end
