/*
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package tv.trakt.trakt.app.core.plex

import io.ktor.client.HttpClientConfig
import io.ktor.client.engine.HttpClientEngine
import io.ktor.client.utils.EmptyContent
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.HttpResponse
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.wrap

internal open class PlexStreamApi(
    baseUrl: String,
    httpClientEngine: HttpClientEngine?,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)?,
) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {
    @Suppress("UNCHECKED_CAST")
    open suspend fun getPlexStream(
        id: String,
        type: String,
    ): HttpResponse<PlexStreamDto> {
        val localVariableAuthNames = listOf<String>()
        val localVariableBody = EmptyContent
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<Any?>(
            RequestMethod.GET,
            "/users/me/plex/stream/$type/$id",
            query = mutableMapOf(),
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames,
        ).wrap()
    }
}

/**
 * {
 *   "stream_url": "https://172-104-62-188.8d7620d3517c46569e6d47d12298b3c9.plex.direct:8443/library/parts/1/file?X-Plex-Token=VCYG2-4ZVWiFRB--p1JA",
 *   "matched_by": {
 *     "type": "plex_guid",
 *     "value": "plex://movie/5d776d1796b655001fe3f320"
 *   }
 * }
 */
@Serializable
internal data class PlexStreamDto(
    @SerialName("stream_url")
    val streamUrl: String?,
    val connections: List<Connection>?,
) {
    @Serializable
    data class Connection(
        val uri: String,
        val local: Boolean,
        val relay: Boolean,
    )
}
