package tv.trakt.trakt.common.networking

import org.openapitools.client.models.GetCalendarsMedia200ResponseInner
import org.openapitools.client.models.GetCalendarsMedia200ResponseInnerEpisode
import org.openapitools.client.models.GetCalendarsMedia200ResponseInnerMovie
import org.openapitools.client.models.GetCalendarsMedia200ResponseInnerShow
import org.openapitools.client.models.GetCalendarsMovies200ResponseInner
import org.openapitools.client.models.GetCalendarsMovies200ResponseInnerMovie
import org.openapitools.client.models.GetCalendarsMovies200ResponseInnerMovieIds
import org.openapitools.client.models.GetCalendarsShows200ResponseInner
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerEpisode
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerEpisodeEpisodesInner
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerEpisodeIds
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerShow
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerShowIds
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerShowImages
import org.openapitools.client.models.GetMoviesPeople200Response
import org.openapitools.client.models.GetMoviesPeople200ResponseCastInnerPerson
import org.openapitools.client.models.GetMoviesRatings200Response
import org.openapitools.client.models.GetMoviesStats200Response
import org.openapitools.client.models.GetMoviesTranslations200ResponseInner
import org.openapitools.client.models.GetMoviesVideos200ResponseInner
import org.openapitools.client.models.GetMoviesWatchnow200ResponseValue
import org.openapitools.client.models.GetMoviesWatchnow200ResponseValueCableInner
import org.openapitools.client.models.GetPeopleMovies200Response
import org.openapitools.client.models.GetPeopleShows200Response
import org.openapitools.client.models.GetRecommendationsMoviesRecommend200ResponseInner
import org.openapitools.client.models.GetRecommendationsShowsRecommend200ResponseInner
import org.openapitools.client.models.GetSearchQuery200ResponseInner
import org.openapitools.client.models.GetSearchQuery200ResponseInnerOneOf2Person
import org.openapitools.client.models.GetSearchQuery200ResponseInnerOneOf3List
import org.openapitools.client.models.GetSearchTrending200ResponseInner
import org.openapitools.client.models.GetShowsEpisodeTranslations200ResponseInner
import org.openapitools.client.models.GetShowsSeasonStats200Response
import org.openapitools.client.models.GetShowsSeasons200ResponseInner
import org.openapitools.client.models.GetSyncCollectionAll200ResponseInner
import org.openapitools.client.models.GetSyncProgressEpisodesResponse
import org.openapitools.client.models.GetSyncProgressMovies200ResponseInner
import org.openapitools.client.models.GetSyncProgressUpNextStandard200ResponseInner
import org.openapitools.client.models.GetSyncProgressUpNextStandard200ResponseInnerProgressNextEpisode
import org.openapitools.client.models.GetUsersActivities200ResponseInner
import org.openapitools.client.models.GetUsersComments200ResponseInner
import org.openapitools.client.models.GetUsersComments200ResponseInnerComment
import org.openapitools.client.models.GetUsersFavoritesMedia200ResponseInnerOneOf
import org.openapitools.client.models.GetUsersFavoritesMedia200ResponseInnerOneOf1
import org.openapitools.client.models.GetUsersHiddenGetBySection200ResponseInner
import org.openapitools.client.models.GetUsersHistoryAll200ResponseInner
import org.openapitools.client.models.GetUsersHistoryMovies200ResponseInner
import org.openapitools.client.models.GetUsersHistoryShows200ResponseInner
import org.openapitools.client.models.GetUsersLikes200ResponseInner
import org.openapitools.client.models.GetUsersLikes200ResponseInnerOneOfAllOfOneOf2Episode
import org.openapitools.client.models.GetUsersLikes200ResponseInnerOneOfAllOfOneOf3Season
import org.openapitools.client.models.GetUsersListsListItemsAll200ResponseInner
import org.openapitools.client.models.GetUsersListsPersonal200ResponseInner
import org.openapitools.client.models.GetUsersRatingsMovies200ResponseInner
import org.openapitools.client.models.GetUsersReactionsComments200ResponseInner
import org.openapitools.client.models.GetUsersReactionsComments200ResponseInnerCommentUser
import org.openapitools.client.models.GetUsersRequestsFollow200ResponseInner
import org.openapitools.client.models.GetUsersSettings200Response
import org.openapitools.client.models.GetUsersWatching200Response
import org.openapitools.client.models.GetUsersWatchlistAll200ResponseInner
import org.openapitools.client.models.GetUsersWatchlistMovies200ResponseInner
import org.openapitools.client.models.GetUsersWatchlistShows200ResponseInner
import org.openapitools.client.models.GetWatchnowSourcesAll200ResponseInnerValueInner
import org.openapitools.client.models.PostSyncHistoryAdd200Response

/**
 * Type aliases for OpenAPI models used in the app.
 */
typealias ShowDto = GetCalendarsMedia200ResponseInnerShow
typealias ShowIdsDto = GetCalendarsShows200ResponseInnerShowIds
typealias ShowStatsDto = GetMoviesStats200Response
typealias ShowCalendarsDto = GetCalendarsShows200ResponseInnerShow

typealias MovieDto = GetCalendarsMedia200ResponseInnerMovie
typealias MovieIdsDto = GetCalendarsMovies200ResponseInnerMovieIds
typealias MovieStatsDto = GetMoviesStats200Response
typealias MovieCalendarDto = GetCalendarsMovies200ResponseInnerMovie

typealias EpisodeDto = GetCalendarsMedia200ResponseInnerEpisode
typealias EpisodeIdsDto = GetCalendarsShows200ResponseInnerEpisodeIds
typealias EpisodeLikesDto = GetUsersLikes200ResponseInnerOneOfAllOfOneOf2Episode
typealias EpisodeStatsDto = GetShowsSeasonStats200Response
typealias EpisodeCalendarsDto = GetCalendarsShows200ResponseInnerEpisodeEpisodesInner
typealias EpisodeCalendarDto = GetCalendarsShows200ResponseInnerEpisode
typealias LastEpisodeDto = GetSyncProgressUpNextStandard200ResponseInnerProgressNextEpisode

typealias ImagesDto = GetCalendarsShows200ResponseInnerShowImages
typealias ExtraVideoDto = GetMoviesVideos200ResponseInner
typealias CastCrewDto = GetMoviesPeople200Response
typealias ExternalRatingsDto = GetMoviesRatings200Response
typealias PersonDto = GetMoviesPeople200ResponseCastInnerPerson
typealias PersonShowsDto = GetPeopleShows200Response
typealias PersonMoviesDto = GetPeopleMovies200Response
typealias PersonSearchDto = GetSearchQuery200ResponseInnerOneOf2Person
typealias TrendingSearchDto = GetSearchTrending200ResponseInner
typealias CommentDto = GetUsersComments200ResponseInnerComment
typealias CommentAllDto = GetUsersComments200ResponseInner
typealias SeasonDto = GetShowsSeasons200ResponseInner

typealias SeasonLikesDto = GetUsersLikes200ResponseInnerOneOfAllOfOneOf3Season
typealias ListDto = GetUsersListsPersonal200ResponseInner
typealias LikedListDto = GetUsersLikes200ResponseInner
typealias ListMovieItemDto = GetUsersWatchlistMovies200ResponseInner
typealias ListShowItemDto = GetUsersWatchlistShows200ResponseInner
typealias ListMediaItemDto = GetUsersWatchlistAll200ResponseInner
typealias ListItemDto = GetUsersListsListItemsAll200ResponseInner
typealias UserSettingsDto = GetUsersSettings200Response
typealias UserReactionDto = GetUsersReactionsComments200ResponseInner
typealias UserMediaDto = GetUsersReactionsComments200ResponseInnerCommentUser
typealias UserCommentsDto = GetUsersReactionsComments200ResponseInnerCommentUser
typealias UserBlockedDto = GetUsersReactionsComments200ResponseInnerCommentUser
typealias StreamingDto = GetMoviesWatchnow200ResponseValue
typealias StreamingSourceDto = GetWatchnowSourcesAll200ResponseInnerValueInner
typealias StreamingServiceDto = GetMoviesWatchnow200ResponseValueCableInner
typealias WatchlistShowDto = GetUsersWatchlistShows200ResponseInner
typealias WatchlistMovieDto = GetUsersWatchlistMovies200ResponseInner
typealias WatchlistItemDto = GetUsersWatchlistAll200ResponseInner
typealias CalendarShowDto = GetCalendarsShows200ResponseInner
typealias CalendarMediaDto = GetCalendarsMedia200ResponseInner
typealias CalendarMovieDto = GetCalendarsMovies200ResponseInner
typealias ProgressShowDto = GetSyncProgressUpNextStandard200ResponseInner
typealias ProgressMovieDto = GetSyncProgressMovies200ResponseInner
typealias ProgressEpisodeDto = GetSyncProgressEpisodesResponse
typealias SyncAddHistoryResponseDto = PostSyncHistoryAdd200Response
typealias SyncHistoryMovieItemDto = GetUsersHistoryMovies200ResponseInner
typealias SyncHistoryEpisodeItemDto = GetUsersHistoryShows200ResponseInner
typealias SyncHistoryItemDto = GetUsersHistoryAll200ResponseInner
typealias SyncFavoriteShowDto = GetUsersFavoritesMedia200ResponseInnerOneOf
typealias SyncFavoriteMovieDto = GetUsersFavoritesMedia200ResponseInnerOneOf1
typealias SyncLibraryMediaDto = GetSyncCollectionAll200ResponseInner
typealias RecommendedMovieDto = GetRecommendationsMoviesRecommend200ResponseInner
typealias RecommendedShowDto = GetRecommendationsShowsRecommend200ResponseInner
typealias SearchItemDto = GetSearchQuery200ResponseInner
typealias SearchListDto = GetSearchQuery200ResponseInnerOneOf3List
typealias SocialActivityItemDto = GetUsersActivities200ResponseInner
typealias UserRatingDto = GetUsersRatingsMovies200ResponseInner
typealias DroppedItemDto = GetUsersHiddenGetBySection200ResponseInner
typealias TranslationDto = GetMoviesTranslations200ResponseInner
typealias EpisodeTranslationDto = GetShowsEpisodeTranslations200ResponseInner
typealias UserFollowRequestDto = GetUsersRequestsFollow200ResponseInner

// typealias CheckInMovieResponseDto = PostCheckinMovie200Response
typealias UserWatchingDto = GetUsersWatching200Response
