package tv.trakt.trakt.common.networking

import org.openapitools.client.models.GetCalendarsMovies200ResponseInnerMovie
import org.openapitools.client.models.GetCalendarsMovies200ResponseInnerMovieIds
import org.openapitools.client.models.GetCalendarsShows200ResponseInner
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerEpisode
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerEpisodeIds
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerShow
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerShowIds
import org.openapitools.client.models.GetCalendarsShows200ResponseInnerShowImages
import org.openapitools.client.models.GetMoviesPeople200Response
import org.openapitools.client.models.GetMoviesPeople200ResponseCastInnerPerson
import org.openapitools.client.models.GetMoviesRatings200Response
import org.openapitools.client.models.GetMoviesVideos200ResponseInner
import org.openapitools.client.models.GetMoviesWatchnow200ResponseValue
import org.openapitools.client.models.GetMoviesWatchnow200ResponseValueCableInner
import org.openapitools.client.models.GetPeopleMovies200Response
import org.openapitools.client.models.GetPeopleShows200Response
import org.openapitools.client.models.GetPeopleSummary200Response
import org.openapitools.client.models.GetRecommendationsMoviesRecommend200ResponseInner
import org.openapitools.client.models.GetRecommendationsShowsRecommend200ResponseInner
import org.openapitools.client.models.GetSearchQuery200ResponseInner
import org.openapitools.client.models.GetSyncProgressUpNextStandard200ResponseInner
import org.openapitools.client.models.GetSyncProgressUpNextStandard200ResponseInnerProgressLastEpisode
import org.openapitools.client.models.GetUsersComments200ResponseInnerOneOf2Season
import org.openapitools.client.models.GetUsersComments200ResponseInnerOneOfComment
import org.openapitools.client.models.GetUsersFavoritesMovies200ResponseInner
import org.openapitools.client.models.GetUsersFavoritesShows200ResponseInner
import org.openapitools.client.models.GetUsersHistoryAll200ResponseInnerOneOf
import org.openapitools.client.models.GetUsersHistoryAll200ResponseInnerOneOf1
import org.openapitools.client.models.GetUsersLikesComments200ResponseInnerAllOfOneOf1Show
import org.openapitools.client.models.GetUsersLikesComments200ResponseInnerAllOfOneOfMovie
import org.openapitools.client.models.GetUsersListsPersonal200ResponseInner
import org.openapitools.client.models.GetUsersReactionsComments200ResponseInnerCommentUser
import org.openapitools.client.models.GetUsersSettings200Response
import org.openapitools.client.models.GetUsersSettings200ResponseUser
import org.openapitools.client.models.GetUsersWatchedMovies200ResponseInner
import org.openapitools.client.models.GetUsersWatchedShows200ResponseInner
import org.openapitools.client.models.GetUsersWatchlistMovies200ResponseInner
import org.openapitools.client.models.GetUsersWatchlistShows200ResponseInner
import org.openapitools.client.models.GetWatchnowSourcesAll200ResponseInnerValueInner
import org.openapitools.client.models.PostSyncHistoryAdd200Response

/**
 * Type aliases for OpenAPI models used in the app.
 */
typealias ShowDto = GetCalendarsShows200ResponseInnerShow
typealias ShowIdsDto = GetCalendarsShows200ResponseInnerShowIds
typealias ShowLikesDto = GetUsersLikesComments200ResponseInnerAllOfOneOf1Show

typealias MovieDto = GetCalendarsMovies200ResponseInnerMovie
typealias MovieIdsDto = GetCalendarsMovies200ResponseInnerMovieIds
typealias MovieLikesDto = GetUsersLikesComments200ResponseInnerAllOfOneOfMovie

typealias EpisodeDto = GetCalendarsShows200ResponseInnerEpisode
typealias LastEpisodeDto = GetSyncProgressUpNextStandard200ResponseInnerProgressLastEpisode
typealias EpisodeIdsDto = GetCalendarsShows200ResponseInnerEpisodeIds

typealias ImagesDto = GetCalendarsShows200ResponseInnerShowImages
typealias ExtraVideoDto = GetMoviesVideos200ResponseInner
typealias CastCrewDto = GetMoviesPeople200Response
typealias ExternalRatingsDto = GetMoviesRatings200Response
typealias PersonDto = GetMoviesPeople200ResponseCastInnerPerson
typealias PersonDetailsDto = GetPeopleSummary200Response
typealias PersonShowsDto = GetPeopleShows200Response
typealias PersonMoviesDto = GetPeopleMovies200Response
typealias CommentDto = GetUsersComments200ResponseInnerOneOfComment
typealias SeasonDto = GetUsersComments200ResponseInnerOneOf2Season
typealias ListDto = GetUsersListsPersonal200ResponseInner
typealias ListMovieItemDto = GetUsersWatchlistMovies200ResponseInner
typealias ListShowItemDto = GetUsersWatchlistShows200ResponseInner
typealias UserDto = GetUsersSettings200ResponseUser
typealias UserSettingsDto = GetUsersSettings200Response
typealias UserCommentsDto = GetUsersReactionsComments200ResponseInnerCommentUser
typealias StreamingDto = GetMoviesWatchnow200ResponseValue
typealias StreamingSourceDto = GetWatchnowSourcesAll200ResponseInnerValueInner
typealias StreamingServiceDto = GetMoviesWatchnow200ResponseValueCableInner
typealias WatchlistShowDto = GetUsersWatchlistShows200ResponseInner
typealias WatchlistMovieDto = GetUsersWatchlistMovies200ResponseInner
typealias CalendarShowDto = GetCalendarsShows200ResponseInner
typealias ProgressShowDto = GetSyncProgressUpNextStandard200ResponseInner
typealias WatchedShowDto = GetUsersWatchedShows200ResponseInner
typealias WatchedMovieDto = GetUsersWatchedMovies200ResponseInner
typealias SyncAddHistoryResponseDto = PostSyncHistoryAdd200Response
typealias SyncHistoryMovieItemDto = GetUsersHistoryAll200ResponseInnerOneOf
typealias SyncHistoryEpisodeItemDto = GetUsersHistoryAll200ResponseInnerOneOf1
typealias SyncFavoriteShowDto = GetUsersFavoritesShows200ResponseInner
typealias SyncFavoriteMovieDto = GetUsersFavoritesMovies200ResponseInner
typealias RecommendedMovieDto = GetRecommendationsMoviesRecommend200ResponseInner
typealias RecommendedShowDto = GetRecommendationsShowsRecommend200ResponseInner
typealias SearchItemDto = GetSearchQuery200ResponseInner
