package tv.trakt.trakt.common.networking.api.scrobble.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import org.openapitools.client.models.PostSyncRatingsRemoveRequestMoviesInner

/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

/**
 *
 *
 * @param progress
 * @param episode
 */
@Serializable
data class PostScrobbleMovieRequest(
    @SerialName(value = "progress")
    val progress: Float,
    @SerialName(value = "movie")
    val movie: PostSyncRatingsRemoveRequestMoviesInner,
)
